name: "nuke"
description: "Builds and tests a .NET project"
inputs:
  directory:
    description: "Project directory"
    required: true
  NuGetApiUrl:
    description: "NuGet Url"
    default: "false"
    required: false
  NuGetApiKey:
    description: "NuGet API Key"
    default: "false"
    required: false
outputs:
  test-results:
    description: Location of the test results file
    value: ${{ steps.dotnet-test.outputs.test-results }}
  test-results-title:
    description: Title of the test results
    value: ${{ steps.dotnet-test.outputs.test-results-title }}
runs:
  using: "composite"
  steps:
    - name: dotnet tool restore
      shell: bash
      working-directory: ${{ inputs.Directory }}
      run: |
        dotnet nuget list source
        dotnet tool restore
    - name: dotnet nuke --target All
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        dotnet nuke --target All
    - name: dotnet nuke --target Push
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        dotnet nuke --target Push --nuget-api-url ${{ inputs.NuGetApiUrl }} --nuget-api-key ${{ secrets.NUGET_API_KEY }}