
name: install-buildkit-ci

# env:
#   NETCORE_VERSION: 6.0.100
#   ACTIONS_ALLOW_UNSECURE_COMMANDS: true
#   DOTNET_ROLL_FORWARD: Major

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
    - main
    - feature/*
    - release/*
    paths:
      - ".github/workflows/install-buildkit-ci.yml"
      - "install-buildkit/**"

jobs:
  install-buildkit:
    name: install-buildkit
    runs-on: ubuntu-latest
    steps:
    - uses: cloud-tek/actions/install-buildkit@main
      with:
        version: "0.1.6"
        architecture: amd64